Patch @smarttools/eslint-plugin-rxjs to v1.0.9
Strict dependency at v1.0.9, because at v1.0.10 linting fails with the error:

> Error TS2307: Cannot find module '@typescript-eslint/utils/ts-eslint' or its corresponding type declarations.
  There are types at '/home/runner/work/eslint-config/eslint-config/node_modules/@typescript-eslint/utils/dist/ts-eslint/index.d.ts', but this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'.